name: make_drake_cron

on:
  push:
    branches: [master]
  schedule:
    # UTC is currently -2 wrt Europe/Stockholm (CEST)
    - cron: "05 12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@master

      - name: renv cache
        uses: actions/cache@v1
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: renv
        run: Rscript -e "renv::restore()"

      - name: build
        run: Rscript -e 'source("batch.R")'

      - name: push
        run: |
          git config --global user.name 'Adam Altmejd'
          git config --global user.email 'adamaltmejd@users.noreply.github.com'
          git add --all
          git commit -m "Github Action autocommit"
          git push
